name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag iyjian/cosyvoice

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWD }}

    - name: Push the Docker image
      run: |
        echo "${{ secrets.DOCKERHUB_PASSWD }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin
        docker push iyjian/cosyvoice:latest
